on:
  workflow_dispatch:

jobs:
  update-apis:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v6
        with:
          node-version: 22
      - run: npm install
      - run: npm run update-disclaimers
      - run: npm run submit-prs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CODE_BOT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
